# Generated by Django 4.2.29 on 2026-03-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['username']},
        ),
    ]
