# Generated by Django 4.2.29 on 2026-03-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_book_comment_bookimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='age',
            new_name='year',
        ),
    ]
